title: Ayush Kulshrestha
logo: "/images/logo.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer
  <br><br>
  Exploring MERN Techstack & Love to build Apps
  <br><br>
  <a href="https://in.linkedin.com/in/ayush-kulshrestha">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
