title: Ayush Kulshrestha
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: >
  Software Developer at Leewayhertz
  <br><br>
  Exploring MERN Techstack <br>Love to build Apps
  <br>
  <a href="https://in.linkedin.com/in/ayush-kulshrestha">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
