title: Ayush Kulshrestha
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: >
  <b>Software Developer at Leewayhertz</b>
  <br>
  <ul>
    <li>Exploring MERN Techstack</li>
    <li>Love to build Apps</li>
  </ul>
  <br>
  <a href="https://in.linkedin.com/in/ayush-kulshrestha">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
